# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & test

env:
  nexusUsername: ${{ secrets.NEXUS_USERNAME }}
  nexusPassword: ${{ secrets.NEXUS_PASSWORD }}

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build & test with Gradle
        env:
          L1_TEST_NET_RPC_URL: ${{ secrets.L1_TEST_NET_RPC_URL }}
          L2_TEST_NET_RPC_URL: ${{ secrets.L2_TEST_NET_RPC_URL }}
        run: ./gradlew build
